export { VrgFieldTextService } from './vrg-fields-templates/vrg-field-text/vrg-field-text.service'
export { VrgFieldNumberService } from './vrg-fields-templates/vrg-field-number/vrg-field-number.service'
export { VrgFieldPasswordService } from './vrg-fields-templates/vrg-field-password/vrg-field-password.service'
export { VrgFieldTextareaService } from './vrg-fields-templates/vrg-field-textarea/vrg-field-textarea.service'
export { VrgFieldPhoneService } from './vrg-fields-templates/vrg-field-phone/vrg-field-phone.service'
export { VrgFieldEmailService } from './vrg-fields-templates/vrg-field-email/vrg-field-email.service'
export { VrgFieldTemplatesService } from './vrg-form-templates/vrg-field-templates.service'
export { VrgFormBuilder as VrgFormService } from './vrg-form-builder/vrg-form-builder.service'